name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v4
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
      - name: Unit tests
        run: pnpm --filter @botpress/cdk-postgresql test:unit
      - name: Integration tests
        run: pnpm --filter @botpress/cdk-postgresql test:integration
      - name: Synthesize test stack
        run: pnpm --filter myapp synth
        env:
          STACK_NAME: ci
